lib/reducers/createSearchResult.js
lib/reducers/index.js
lib/sagas/searchSuccess.js
test/mocha/reducers/createSearchResult.js
test/mocha/sagas/searchSuccess.js

add getRecordIdsWithMissingLink selector and use it to fetch correct notice on PAGE_LOAD

[RFR] fix link fetch on PAGE_LOAD

---

lib/actions/index.js
lib/components/SearchInput.js
lib/containers/ArticleSearchInput.js
lib/containers/PublicationSearchInput.js
lib/reducers/createQueryList.js
lib/reducers/index.js
lib/sagas/autoComplete.js
lib/sagas/index.js
lib/sass/_Search.scss
test/mocha/reducers/createQueryList.js
test/mocha/sagas/autocomplete.js

Waiting for working ebsco autocomplete route.

[RFR]Autocomplete

---

lib/actions/index.js
lib/components/SearchInput.js
lib/containers/ArticleSearchInput.js
lib/containers/PublicationSearchInput.js
lib/reducers/createQueryList.js
lib/sagas/autoComplete.js
lib/sagas/exactMatch.js
lib/sagas/search.js
test/mocha/reducers/createQueryList.js
test/mocha/sagas/autocomplete.js

https://trello.com/c/eNSn3BGl/7-0-25-bibcnrs-la-touche-entree-dans-la-recherche-d-un-article-n-execute-pas-la-fonction-d-exact-placard-match
et
https://trello.com/c/9UsXySx4/4-0-5-bibcnrs-la-liste-des-termes-d-auto-completion-ne-doit-pas-rester-affichee-des-lors-que-l-utilisateur-a-clique-sur-la-touche-

[RFR]Fix exact Match placard et autocompletion

---

lib/sagas/loginSuccess.js
lib/selectors/index.js
test/mocha/sagas/loginSuccess.js

https://trello.com/c/hH872SK5/8-1-bibcnrs-dans-la-recherche-une-revue-un-ouvrage-solution-ergonomique-a-mettre-en-place-pour-que-l-utilisateur-se-trouve-par-def

[RFR] change publication domain on login when no search result

---

lib/actions/index.js
lib/components/App.js
lib/components/BibNavbar.js
lib/components/Profile.js
lib/containers/BibNavbar.js
lib/containers/Profile.js
lib/higherOrderComponents/addTooltip.js
lib/reducers/domains.js
lib/reducers/index.js
lib/reducers/profile.js
lib/reducers/userInterface.js
lib/sagas/apiUpdateProfile.js
lib/sagas/index.js
lib/sagas/loginSuccess.js
lib/selectors/index.js
mock/server.js
test/e2e/test/articleSearch.json
test/e2e/test/articleSearchResult.json
test/e2e/test/authentication.json
test/e2e/test/authenticationModal.json
test/e2e/test/history.json
test/e2e/test/publicationSearch.json
test/e2e/test/publicationSearchResult.json
test/mocha/reducers/profile.js
test/mocha/reducers/userInterface.js
test/mocha/sagas/apiUpdateProfile.js

[Trello card](https://trello.com/c/VDeIu3O1/23-2-bibcnrs-en-tant-qu-utilisateur-janus-je-veux-pouvoir-enregistrer-mon-domaine-prefere)

[RFR] Favorite domain

---

lib/components/Error.js
lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/sagas/showNotice.js
test/mocha/sagas/showNotice.js

[Trello card](https://trello.com/c/SY5gvbHw/15-0-5-bibcnrs-modifier-le-libelle-des-messages-d-erreur-unauthorized)

[RFR] Customize 401 messages when accessing unauthorized documents

---

lib/components/BibNavbar.js
lib/components/Profile.js
lib/containers/BibNavbar.js
lib/reducers/profile.js
lib/reducers/userInterface.js
lib/selectors/index.js
test/mocha/reducers/profile.js

Needs https://github.com/BibCnrs/BibApi/pull/136

[RFR] Ensure profile feature is only available to janus accounts

---

lib/components/Error.js
lib/components/Profile.js
lib/config/i18n/en.js
lib/config/i18n/fr.js

[Trello card](https://trello.com/c/VDeIu3O1/)

[RFR] Wording for error messages and profile dialog

---

lib/actions/index.js
lib/containers/EbscoWidget.dev.js
lib/containers/EbscoWidget.prod.js
lib/containers/getSearchParametersFromUrl.js
lib/index.js
lib/reducers/createQueryList.js
lib/reducers/domains.js
lib/reducers/userInterface.js
lib/sagas/initialize.js
lib/sagas/loginSuccess.js
lib/selectors/index.js
lib/store/store.dev.js
lib/store/store.prod.js
package.json
test/mocha/reducers/userInterface.js
test/mocha/sagas/initialize.js
test/mocha/sagas/loginSuccess.js

[Trello card](https://trello.com/c/Rp8WUJR8)
Querystring parameters are:
- `domain`: the domain on which to search
- `type`: `article` or `publication`
- `term`: the term to search for

[RFR] Initialize search from url querystring

---

lib/components/A2zSearch.js
test/e2e/test/publicationSearch.js

[Trello card](https://trello.com/c/p8CxOii6)

[RFR] Fix letters filtering

---

lib/actions/index.js
lib/components/History.js
lib/containers/History.js
lib/reducers/history.js
lib/reducers/profile.js
lib/sagas/apiDeleteHistory.js
lib/sagas/apiLoadHistoryPage.js
lib/sagas/apiPersistHistory.js
lib/sagas/history.js
lib/sagas/index.js
lib/sagas/initialize.js
lib/sagas/loginSuccess.js
lib/selectors/index.js
test/e2e/test/articleSearch.json
test/e2e/test/articleSearchResult.json
test/e2e/test/authentication.json
test/e2e/test/authenticationModal.json
test/e2e/test/history.json
test/e2e/test/publicationSearch.json
test/e2e/test/publicationSearchResult.json
test/mocha/reducers/history.js
test/mocha/reducers/profile.js
test/mocha/sagas/apiDeleteHistory.js
test/mocha/sagas/apiLoadHistoryPage.js
test/mocha/sagas/history.js
test/mocha/sagas/initialize.js
test/mocha/sagas/loginSuccess.js

[Trello card](https://trello.com/c/hI6mHSlb)

[RFR] Persist janus accounts history

---

lib/components/DomainSelector.js
lib/containers/getSearchParametersFromUrl.js
lib/reducers/domains.js
test/mocha/reducers/domains.js

[RFR] Sanitize url parameters 

---

lib/reducers/history.js
lib/selectors/index.js

[Trello card](https://trello.com/c/Rp8WUJR8)

[RFR] Fix url domain change after login

---

lib/components/Blob.js
package-lock.json
package.json
test/mocha/components/Blob.js

[RFR]Math formula

---

lib/components/BibNavbar.js
lib/sass/_NavBar.scss

[RFR] display navbar with style tabs

---

lib/reducers/createSearch.js
test/mocha/reducers/createSearch.js

depends on https://github.com/BibCnrs/BibApi/pull/154

[RFR] A2z sort title

---

lib/components/ArticleLink.js
lib/components/ArticleRecord.js
lib/containers/createRecordContainer.js
lib/reducers/domains.js
lib/sagas/initialize.js
lib/selectors/index.js
lib/services/parseArticleLinks.js
test/e2e/test/articleSearch.json
test/e2e/test/articleSearchResult.json
test/e2e/test/authentication.json
test/e2e/test/authenticationModal.json
test/e2e/test/history.json
test/e2e/test/publicationSearch.json
test/e2e/test/publicationSearchResult.json
test/mocha/reducers/domains.js
test/mocha/sagas/initialize.js
test/mocha/services/parseArticleLinks.js

linked to https://github.com/BibCnrs/BibApi/pull/156

[RFR] Pdf proxify

---

lib/components/ArticleSearchMenu.js
lib/components/PublicationSearchMenu.js
lib/components/ShowResultButton.js
lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/sass/_SearchMenu.scss

Waiting for english translation
test fixed in https://github.com/BibCnrs/EBSCO-widget/pull/182

[RFR]Show result popin

---

lib/components/ArticleLink.js
lib/services/parseArticleLinks.js
test/mocha/services/parseArticleLinks.js

test fixed in https://github.com/BibCnrs/EBSCO-widget/pull/182

[RFR] Download html ie

---

lib/sass/_Header.scss

fix https://bibcnrs.slack.com/files/U957YNQ93/F9K625UHJ/image.png issue

[RFR] augment header infos width to avoid out of bound domains

---

lib/components/FavouriteResourceItem.js
lib/components/FavouriteResourceList.js
lib/components/Profile.js
lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/containers/FavouriteResourceList.js
lib/reducers/favouriteResources.js
lib/reducers/index.js
lib/sass/_FavouriteResources.scss
lib/sass/style.scss
lib/selectors/index.js
test/mocha/reducers/favouriteResources.js

https://trello.com/c/xXn8RRZg/106-2-option-3-bibcnrs-initialisation-des-ressources-favorites-pour-lutilisateur

[RFR] Favourite ressources

---

lib/actions/index.js
lib/components/BookmarkButton.js
lib/components/Database.js
lib/components/FavouriteResourceItem.js
lib/components/FavouriteResourceList.js
lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/containers/BookmarkButton.js
lib/containers/FavouriteResourceList.js
lib/reducers/favouriteResources.js
lib/sagas/updateFavouriteResources.js
lib/sass/_FavouriteResources.scss
test/e2e/test/profile.js
test/e2e/test/profile.json
test/mocha/reducers/favouriteResources.js
test/mocha/sagas/updateFavouriteResources.js

https://trello.com/c/W2DuepEX/108-05-option-3-bibcnrs-suppression-des-ressources-favorites-par-lutilisateur

[RFR] Remove favourite resources

---

lib/actions/index.js
lib/components/BibButton.js
lib/components/DragButton.js
lib/components/FavouriteResourceItem.js
lib/components/FavouriteResourceList.js
lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/containers/FavouriteResourceList.js
lib/reducers/favouriteResources.js
lib/sagas/updateFavouriteResources.js
lib/sass/_FavouriteResources.scss
package-lock.json
package.json
test/mocha/reducers/favouriteResources.js

https://trello.com/c/834ZHWg8/38-1-option-3-bibcnrs-modifier-lordre-des-ressources-favorites-par-lutilisateur

[RFR] Reorder favourite resource

---

lib/components/GoogleScholarParameter.js
lib/components/Profile.js
lib/config/i18n/en.js
lib/config/i18n/fr.js

[RFR] add google scholar tab in profile

---

lib/components/App.js
lib/components/ArticleRecordTitleLink.js
lib/components/Authentication.js
lib/components/FullTextHolding.js
lib/higherOrderComponents/addTooltip.js
package-lock.json
package.json

PR pour réduire le nombre de warning
(Note: les warnings concernant activeHref et activeKey ne sont pas résolvables en l'éat)

reduce number warning

---

lib/components/Database.js
lib/components/DatabaseItem.js
lib/reducers/domains.js
lib/sass/_Database.scss

- oa displayed when not connected
- link on block instead of only title

fix bug and feedback UX for database

---

lib/components/PublicationRecord.js
lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/sass/_Record.scss

Feat: Add diamond icon for revue

---

lib/components/FavouriteResourceItem.js
lib/components/FavouriteResourceList.js
lib/components/PersonalResourceItem.js
lib/components/PersonalResourceList.js
lib/components/Profile.js
lib/containers/FavouriteResourceList.js
lib/containers/PersonalResourceList.js
lib/sass/_FavouriteResources.scss
test/e2e/test/profile.js

https://user-images.githubusercontent.com/41492953/197878754-19940893-ffee-4a70-ab5c-0d84c5456717.mov

Feat: improve favourite resources list

---

lib/sass/_Search.scss
lib/sass/_SearchDomains.scss
package-lock.json

Feat: Update design of chips

---

lib/reducers/createSearchResult.js

Feat: do not call unpaywall for retrieve articles

---

lib/config/i18n/en.js
lib/config/i18n/fr.js
lib/sagas/search.js

Feat: display custom error message for 503 from metadore api

---

lib/actions/index.js
lib/components/History.js
lib/sagas/disableAllAlert.js

https://user-images.githubusercontent.com/41492953/202748806-c2c3946e-58a9-4dde-a2df-a08d5241f6ac.mov

Fix: keep current results per page when toggle alerts
